#!/usr/bin/env python

# get list of valid ssl symlinks
import os
import re
config = '/etc/ca-certificates.conf'
local_certs = '/usr/local/share/ca-certificates'
certs_dir = '/etc/ssl/certs'
certs = set()
for l in open(config, 'r'):
    # lines prefix by an exclamation mark should have been removed by
    # the update-ca-certificates script
    if not re.match('^$|^#|^!', l):
        certs.add(os.path.basename(l.strip()))
if os.path.exists(local_certs):
    for root, dirs, files in os.walk(local_certs):
        for f in files:
            if os.path.splitext(f)[1] == '.crt':
                certs.add(f)
pem = [os.path.join(certs_dir, os.path.splitext(c)[0] + '\.pem') for c in certs]
for p in pem:
    print('^' + p + '$')

# ignore hash links
import subprocess
for p in pem:
    h = subprocess.Popen('openssl x509 -hash -noout -in ' + p,
                         shell=True,
                         stdout=subprocess.PIPE).communicate()[0].strip(os.linesep)
    print('^' + os.path.join(certs_dir, h) + '\.[0-9]+$')

# generated bundle file
print('^' + os.path.join(certs_dir, 'ca-certificates\.crt$'))
