#!/bin/bash

# ignore src tree symlink
echo ^/usr/src/linux$

# ignore objects depending on kernel release
kernel_r=`uname -r`
echo ^/boot/config{,\.old,-$kernel_r}$
echo ^/boot/vmlinuz{,\.old,-$kernel_r}$
echo ^/boot/System.map{,\.old,-$kernel_r}$
echo ^/boot/`ls -l /boot/config.old | awk '{print $NF}'`$
echo ^/boot/`ls -l /boot/vmlinuz.old | awk '{print $NF}'`$
echo ^/boot/`ls -l /boot/System.map.old | awk '{print $NF}'`$
echo ^/lib{,64}/modules/$kernel_r$
echo ^/usr/src/linux-$kernel_r$
