#!/usr/bin/env python

## traverse portage contents
#import portage
#import re
#vardb = portage.db[portage.root]["vartree"].dbapi
#la_regex = re.compile('.*/lib.*\.la$')
#keep_regex = re.compile('^/var/run/.*/.keep_')
#for pkg in sorted(vardb.cpv_all()):
#  contents = vardb._dblink(pkg).getcontents()
#  for k in contents.keys():
# 
#    # exclude portage controlled la files from sanity checks which might
#    # have been modified by lafilefixer.
#    # in the long run these la files will disappear:
#    # http://bugs.gentoo.org/271129
#    if la_regex.match(k):
#      regex = k
#      regex = regex.replace('+', '\+')
#      regex = regex.replace('.', '\.')
#      print('^' + regex + '$')
# 
#    # exclude portage controlled keep files from sanity checks which get
#    # constantly overwritten by initscripts
#    if keep_regex.match(k):
#      regex = k
#      regex = regex.replace('+', '\+')
#      regex = regex.replace('.', '\.')
#      print('^' + regex + '$')
