#!/bin/bash

# ignore objects depending on architecture
machine=`uname -m`
if [[ "$machine" == 'x86_64' ]]; then
    # the mandatory symlink to lib64 is not owned by any package
    echo ^/lib$
    echo ^/usr/lib$
    echo ^/usr/local/lib$
fi

# exclude adm_config stuff
echo ^/.git$
adm_config.py list | sed 's/[^\/]*\(\/.*\)/\1/' | sed 's/\(\/.*\)/\1/' | sed 's/\+/\\+/g' | sed 's/\./\\./g' | sed 's/\(.*\)/^\1$/'; test ${PIPESTATUS[0]} -eq 0
